name: Publish to npm

on: workflow_dispatch

env:
  NODE_VERSION: '24'

jobs:
  publish:
    if: github.repository == 'tomherni/quote-quote' # Don't run on forks.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Linting
        run: npm run lint:check

      - name: Formatting
        run: npm run format:check

      - name: Create build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm publish
