name: Publish to npm

on: workflow_dispatch

env:
  NODE_VERSION: '20'

jobs:
  publish:
    if: github.repository == 'tomherni/quote-quote' # Don't run on forks.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # For npm provenance publish.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint:check

      - name: Formatting
        run: npm run format:check

      - name: Create build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACCESS_TOKEN }}
